// This file is auto-generated by @hey-api/openapi-ts

export type User = {
    created_at?: string;
    designed_question_id?: Array<(string)>;
    email?: string;
    first_name?: string;
    id?: number;
    last_name?: string;
};

export type UserCreate = {
    email: string;
    first_name: string;
    last_name: string;
};

export type UserDelete = {
    email: string;
};

export type UserUpdate = {
    current_email: string;
    first_name: string;
    last_name: string;
    new_email?: string;
};

export type OptionsApiUserCreateUserData = {
    body?: UserCreate;
};

export type OptionsApiUserCreateUserResponse = (User);

export type PostApiUserCreateUserData = {
    body?: UserCreate;
};

export type PostApiUserCreateUserResponse = (User);

export type DeleteApiUserDeleteUserByUserIdData = {
    body?: UserDelete;
    userId: number;
};

export type DeleteApiUserDeleteUserByUserIdResponse = (User);

export type OptionsApiUserDeleteUserByUserIdData = {
    body?: UserDelete;
    userId: number;
};

export type OptionsApiUserDeleteUserByUserIdResponse = (User);

export type OptionsApiUserUpdateUserByUserIdData = {
    body?: UserUpdate;
    userId: number;
};

export type OptionsApiUserUpdateUserByUserIdResponse = (User);

export type PatchApiUserUpdateUserByUserIdData = {
    body?: UserUpdate;
    userId: number;
};

export type PatchApiUserUpdateUserByUserIdResponse = (User);

export type GetApiUserUsersResponse = (Array<User>);

export type OptionsApiUserUsersResponse = (Array<User>);