"""change question table

Revision ID: 6ba3addb094b
Revises: 146334ef972d
Create Date: 2024-12-25 12:16:52.125920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ba3addb094b'
down_revision = '146334ef972d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.String(), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('rank',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('rank',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('answer')

    # ### end Alembic commands ###
