"""update db relation key

Revision ID: 6f25e15533bc
Revises: 6ba3addb094b
Create Date: 2025-01-05 19:19:11.925278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f25e15533bc'
down_revision = '6ba3addb094b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('designed_question_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designed_question_id', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
