"""update db foreignkey delete

Revision ID: a5a9bd04f894
Revises: 5ffdb4df2547
Create Date: 2025-01-06 14:25:03.489007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a9bd04f894'
down_revision = '5ffdb4df2547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint('question_designed_by_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['designed_by_user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('question_designed_by_user_id_fkey', 'users', ['designed_by_user_id'], ['id'])

    # ### end Alembic commands ###
