"""update User table datetime

Revision ID: d4e8e346cc68
Revises: 7bfd023a4238
Create Date: 2024-12-02 22:37:32.569598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e8e346cc68'
down_revision = '7bfd023a4238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_created_at', ['created_at'], unique=False)

    # ### end Alembic commands ###
